import { Router, Request, Response } from 'express';
import { z } from 'zod';
import FHIRBundle from '../models/FHIRBundle.js';

const router = Router();

const fhirBodySchema = z.object({
  patientId: z.string().min(1, 'patientId is required'),
  namasteCode: z.string().min(1, 'namasteCode is required'),
  icd11Code: z.string().min(1, 'icd11Code is required'),
  icd11Title: z.string().min(1, 'icd11Title is required'),
  conditionName: z.string().min(1, 'conditionName is required'),
});

router.post('/bundle', async (req: Request, res: Response) => {
  try {
    const parsed = fhirBodySchema.safeParse(req.body);

    if (!parsed.success) {
      const message = parsed.error.issues[0]?.message ?? 'Invalid request body';
      return res.status(400).json({ error: message });
    }

    const { patientId, namasteCode, icd11Code, icd11Title, conditionName } = parsed.data;

    const bundle = {
      resourceType: 'Bundle',
      id: `ayushbridge-${Date.now()}`,
      type: 'document',
      timestamp: new Date().toISOString(),
      entry: [
        {
          resource: {
            resourceType: 'Patient',
            id: patientId,
            text: {
              status: 'generated',
              div: `<div>Patient ${patientId}</div>`,
            },
          },
        },
        {
          resource: {
            resourceType: 'Condition',
            id: `condition-${Date.now()}`,
            clinicalStatus: {
              coding: [
                {
                  system: 'http://terminology.hl7.org/CodeSystem/condition-clinical',
                  code: 'active',
                },
              ],
            },
            code: {
              coding: [
                {
                  system: 'https://namaste.ayush.gov.in',
                  code: namasteCode,
                  display: conditionName,
                },
                {
                  system: 'http://hl7.org/fhir/sid/icd-11',
                  code: icd11Code,
                  display: icd11Title,
                },
              ],
              text: conditionName,
            },
            subject: {
              reference: `Patient/${patientId}`,
            },
            recordedDate: new Date().toISOString(),
          },
        },
        {
          resource: {
            resourceType: 'Provenance',
            id: `provenance-${Date.now()}`,
            target: [{ reference: `Condition/condition-${Date.now()}` }],
            recorded: new Date().toISOString(),
            agent: [
              {
                type: {
                  coding: [
                    {
                      system: 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType',
                      code: 'AUT',
                      display: 'Author',
                    },
                  ],
                },
                who: { display: 'AyushBridge System' },
              },
            ],
            entity: [
              {
                role: 'source',
                what: { display: 'NAMASTE Coding System' },
              },
            ],
          },
        },
      ],
    };

    await FHIRBundle.create({
      patientId,
      namasteCode,
      icd11Code,
      bundleJSON: bundle,
      auditLog: `Generated by AyushBridge at ${new Date().toISOString()}`,
    });

    return res.status(200).json(bundle);

  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: 'FHIR bundle generation failed' });
  }
});

export default router;